site_name: Electrolama
repo_url: https://github.com/electrolama/docs
plugins: []
markdown_extensions:
  - codehilite
theme:
  name: readthedocs
  custom_dir: 'tweaks/'
  include_search_page: false
  search_index_only: true
  prev_next_buttons_location: none
  navigation_depth: 4
extra_css: [_assets/css/electrolama.css]
google_analytics: ['UA-162410991-1', 'electrolama.com']